spring.application.name=cafedebarrio

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cafedebarrio;encrypt=true;trustServerCertificate=true
spring.datasource.username=cafeuser
spring.datasource.password=cafe123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=${JWT_SECRET:8BEF527F114632CBD4A8EE5FFEB4FC6713BDC1D51045D78B69FF6FC4592D99B3418DF88DC427F21B80F2CDB33378B263}
jwt.expiration=${JWT_EXPIRATION:86400000}